# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro', models.FloatField()),
                ('segundo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Lineal_metodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i', models.FloatField()),
                ('div', models.FloatField()),
                ('mod', models.FloatField()),
                ('xo', models.FloatField()),
                ('nr', models.FloatField()),
            ],
        ),
    ]
