# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('aleatorios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuadrado_metodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('d', models.FloatField()),
                ('nr', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Multiplicativo_metodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.FloatField()),
                ('xo', models.FloatField()),
                ('m', models.FloatField()),
                ('n', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='lineal_metodo',
            old_name='div',
            new_name='a',
        ),
        migrations.RenameField(
            model_name='lineal_metodo',
            old_name='i',
            new_name='c',
        ),
        migrations.RenameField(
            model_name='lineal_metodo',
            old_name='mod',
            new_name='m',
        ),
        migrations.RenameField(
            model_name='lineal_metodo',
            old_name='nr',
            new_name='n',
        ),
    ]
